### ISSUE TITLE
Extension Tags should be changed from (Paid Download / Free)

### ISSUE THREAD

**Issue by shoulders** [joomla-projects/Joomla-Extension-Directory#12]
The current tags are as follows

- Free
- Paid Download

These no longer reflect current products. Some companies make a single listing for a product that has free and a paid version with more features. so to cover these extensions the following should be used

- Free
- Paid
- Free/Paid

You will note that `Paid Download` has been shortened so it matches the other tags

An example extension is: [Convert Forms ](https://extensions.joomla.org/extension/contacts-and-feedback/contact-forms/convert-forms/)

You could also use the tag `lite` for a crippled version of a extension as it implies there is another extension that is paid and has more features. There would also need to be another listing for this full version of the extension.

You could also instead of `Free/Paid` show both tags (`Free` and `Paid`), but I am not 100% how this will affected peoples searches.

**Comment by mfleeson** [comment]
The whole method of classification was redesigned so that any extension can have different supply types, Free, Paid and any other types we choose. Each extension can also have Tags. So this issue is actually a non issue.

**Comment by shoulders** [comment]
> Each extension can also have Tags. So this issue is actually a non issue.

This is an issue because extension developers ake and extension `Free` and it is crippled, but for a fee it can be upgraded to `Pro`. This to me is not free and this is where the `Free/Paid` option comes in, you could also use the term `Lite`
