### ISSUE TITLE
Installation of dev environment

### ISSUE THREAD

**Issue by Elfangor93** [joomla-projects/Joomla-Extension-Directory#26]
I tried to install this repo locally for helping development.
I followed the steps described in https://github.com/joomla-projects/Joomla-Extension-Directory#build-instructions

After running `.\build-windows-c.bat` in the command line I get the following error:

![grafik](https://github.com/joomla-projects/Joomla-Extension-Directory/assets/39154009/884ad49a-991f-42eb-95df-34d129a785b1)
![grafik](https://github.com/joomla-projects/Joomla-Extension-Directory/assets/39154009/7cbee550-2672-484a-afc6-f92f3a3a67c7)

Nevertheless I tried to continue by doing the mapping into my local webserver with `.\vendor\bin\robo map 'D:\wamp64\www\jed4-dev'` and it seems to work anyway.
I guess it is just not able to create the installable zip package file...

### My environment
- Windows NT 10.0 build 19045 (Windows 10) AMD64
- PHP v8.2.7
- Composer version 2.6.6 2023-12-08 18:32:26

**Comment by ramalama** [comment]
I ran into the same problem now and tracked it down to a bug. I suggested a fix in pullrequest https://github.com/joomla-projects/jorobo/pull/86

**Comment by Hackwar** [comment]
I merged the fix and updated the dependencies of this repo to make this work. Can you check if this works for you and then close this issue?

**Comment by mfleeson** [comment]
Tested and working
